In [28]:
import h2o
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ------------------------------------------------------------------
H2O cluster uptime:         1 hour 7 mins
H2O cluster timezone:       Europe/Paris
H2O data parsing timezone:  UTC
H2O cluster version:        3.28.0.3
H2O cluster version age:    23 days
H2O cluster name:           H2O_from_python_edu_gao87u
H2O cluster total nodes:    1
H2O cluster free memory:    1.871 Gb
H2O cluster total cores:    8
H2O cluster allowed cores:  8
H2O cluster status:         locked, healthy
H2O connection url:         http://localhost:54321
H2O connection proxy:       {'http': None, 'https': None}
H2O internal security:      False
H2O API Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python version:             3.7.6 final
--------------------------  ------------------------------------------------------------------

In [29]:
from h2o.estimators.gbm import H2OGradientBoostingEstimator
diamond_path = '../cleaned-data/01-diamonds-train-cl.csv'
diam_df = h2o.import_file(path=diamond_path).drop(0, axis=1)
diam_df.describe()

Parse progress: |█████████████████████████████████████████████████████████| 100%
Rows:40345
Cols:10

,carat,cut,color,clarity,depth,table,x,y,z,price
type,real,int,int,int,real,real,real,real,real,int
mins,0.2,0.0,1.0,0.0,43.0,43.0,0.0,0.0,0.0,326.0
mean,0.7976990953030115,2.905936299417525,4.40651877556079,2.5241293840624612,61.7497211550378,57.449421241789565,5.7308236460527935,5.734807782872725,3.537958111290122,3931.902243152807
maxs,5.01,4.0,7.0,7.0,79.0,95.0,10.74,58.9,8.06,18823.0
sigma,0.47430905911318594,1.1154151728126476,1.7006671128832476,1.839946880272431,1.4277278054903706,2.234087256614312,1.1217667368900286,1.1515362870115242,0.695039090575716,3994.318831718142
zeros,0,1202,0,6092,0,0,4,3,14,0
missing,0,0,0,0,0,0,0,0,0,0
0,0.78,3.0,5.0,0.0,61.5,58.0,5.93,5.98,3.66,3446.0
1,0.31,4.0,7.0,1.0,60.8,56.0,4.37,4.32,2.64,732.0
2,0.3,4.0,5.0,1.0,62.3,54.0,4.3,4.34,2.69,475.0
3,1.04,4.0,6.0,2.0,62.0,58.0,6.54,6.46,4.03,9552.0
4,0.65,4.0,1.0,1.0,61.4,55.0,5.58,5.62,3.44,1276.0
5,0.9,3.0,6.0,3.0,62.2,60.0,6.15,6.19,3.84,3662.0
6,0.31,2.0,3.0,1.0,62.3,55.0,4.34,4.36,2.71,446.0
7,0.71,0.0,6.0,4.0,64.6,59.0,5.62,5.59,3.62,2902.0
8,2.05,4.0,6.0,1.0,62.4,57.0,8.17,8.09,5.08,18193.0
9,1.1,2.0,6.0,1.0,61.3,58.0,6.64,6.71,4.09,4791.0

In [30]:
diam_df_train = diam_df.drop(0, axis=1)
print(list(enumerate(diam_df_train.columns)))
diam_df_train

[(0, 'cut'), (1, 'color'), (2, 'clarity'), (3, 'depth'), (4, 'table'), (5, 'x'), (6, 'y'), (7, 'z'), (8, 'price')]

cut,color,clarity,depth,table,x,y,z,price
3,5,0,61.5,58,5.93,5.98,3.66,3446
4,7,1,60.8,56,4.37,4.32,2.64,732
4,5,1,62.3,54,4.3,4.34,2.69,475
4,6,2,62,58,6.54,6.46,4.03,9552
4,1,1,61.4,55,5.58,5.62,3.44,1276
3,6,3,62.2,60,6.15,6.19,3.84,3662
2,3,1,62.3,55,4.34,4.36,2.71,446
0,6,4,64.6,59,5.62,5.59,3.62,2902
4,6,1,62.4,57,8.17,8.09,5.08,18193
2,6,1,61.3,58,6.64,6.71,4.09,4791

In [31]:
gbm_regressor = H2OGradientBoostingEstimator(distribution="gaussian",
ntrees=10, max_depth=4, min_rows=2, learn_rate=0.2)

In [32]:
gbm_regressor.train(x=diam_df_train.columns[:-1], y='price', training_frame=diam_df_train)

gbm Model Build progress: |███████████████████████████████████████████████| 100%

In [33]:
gbm_regressor

Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_model_python_1582981961797_3


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,10.0,10.0,2577.0,4.0,4.0,4.0,16.0,16.0,16.0

ModelMetricsRegression: gbm
** Reported on train data. **

MSE: 1226452.5616471074
RMSE: 1107.4531871131653
MAE: 676.7263226255577
RMSLE: 0.32090632987276124
Mean Residual Deviance: 1226452.5616471074

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-02-29 15:20:25,0.001 sec,0.0,3994.269329,3033.569481,1.595419e+07
1,,2020-02-29 15:20:26,0.038 sec,1.0,3287.903248,2461.257651,1.081031e+07
2,,2020-02-29 15:20:26,0.074 sec,2.0,2738.378769,2019.460410,7.498718e+06
3,,2020-02-29 15:20:26,0.102 sec,3.0,2312.166206,1678.737610,5.346113e+06
4,,2020-02-29 15:20:26,0.132 sec,4.0,1976.495688,1404.441790,3.906535e+06
5,,2020-02-29 15:20:26,0.155 sec,5.0,1722.996375,1193.261965,2.968717e+06
6,,2020-02-29 15:20:26,0.179 sec,6.0,1525.380448,1029.661236,2.326786e+06
7,,2020-02-29 15:20:26,0.199 sec,7.0,1376.277535,905.908887,1.894140e+06
8,,2020-02-29 15:20:26,0.215 sec,8.0,1271.598444,813.314417,1.616963e+06
9,,2020-02-29 15:20:26,0.229 sec,9.0,1191.635565,745.573190,1.419995e+06
10,,2020-02-29 15:20:26,0.243 sec,10.0,1107.453187,676.726323,1.226453e+06

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0        y         1.402777e+12           1.000000    0.849890
1        z         1.379145e+11           0.098315    0.083557
2  clarity         5.439352e+10           0.038776    0.032955
3    color         3.883685e+10           0.027686    0.023530
4        x         1.648812e+10           0.011754    0.009990
5      cut         1.293567e+08           0.000092    0.000078
6    depth         0.000000e+00           0.000000    0.000000
7    table         0.000000e+00           0.000000    0.000000

In [34]:
train, test = diam_df.split_frame([0.8], seed=1234)
gbm_regressor.train(x=train.columns[:-1], y='price', training_frame=train)

gbm Model Build progress: |███████████████████████████████████████████████| 100%

In [35]:
gbm_regressor.predict(test).shape

gbm prediction progress: |████████████████████████████████████████████████| 100%

(7955, 1)

In [36]:
from h2o.estimators.random_forest import H2ORandomForestEstimator

In [37]:
diam_X = diam_df.col_names[:-1]     #last column is price, our desired response variable 
diam_y = diam_df.col_names[-1]

In [38]:
diam_df

carat,cut,color,clarity,depth,table,x,y,z,price
0.78,3,5,0,61.5,58,5.93,5.98,3.66,3446
0.31,4,7,1,60.8,56,4.37,4.32,2.64,732
0.3,4,5,1,62.3,54,4.3,4.34,2.69,475
1.04,4,6,2,62,58,6.54,6.46,4.03,9552
0.65,4,1,1,61.4,55,5.58,5.62,3.44,1276
0.9,3,6,3,62.2,60,6.15,6.19,3.84,3662
0.31,2,3,1,62.3,55,4.34,4.36,2.71,446
0.71,0,6,4,64.6,59,5.62,5.59,3.62,2902
2.05,4,6,1,62.4,57,8.17,8.09,5.08,18193
1.1,2,6,1,61.3,58,6.64,6.71,4.09,4791

In [39]:
diam_forest_v1 = H2ORandomForestEstimator(
    model_id="rf_covType_v1",
    ntrees=100,
    stopping_rounds=2,
    score_each_iteration=True,
    seed=1000000)
diam_forest_v1.train(diam_X, diam_y, training_frame=train, validation_frame=test)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [40]:
diam_forest_v1

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  rf_covType_v1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,22.0,22.0,4096757.0,20.0,20.0,20.0,13874.0,15453.0,14840.954

ModelMetricsRegression: drf
** Reported on train data. **

MSE: 504640.32280053693
RMSE: 710.3804071063172
MAE: 363.9243017902195
RMSLE: 0.12207354888073972
Mean Residual Deviance: 504640.32280053693

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 418885.66127978073
RMSE: 647.2137678385564
MAE: 335.1927374996122
RMSLE: 0.1113102546303575
Mean Residual Deviance: 418885.66127978073

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance,validation_rmse,validation_mae,validation_deviance
0,,2020-02-29 15:20:27,0.001 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-29 15:20:27,0.262 sec,1.0,1076.294994,524.230579,1.158411e+06,1131.391761,551.766427,1.280047e+06
2,,2020-02-29 15:20:27,0.408 sec,2.0,1037.314133,502.309669,1.076021e+06,902.542274,452.480205,8.145826e+05
3,,2020-02-29 15:20:27,0.571 sec,3.0,988.308257,481.866848,9.767532e+05,785.058501,404.036113,6.163168e+05
4,,2020-02-29 15:20:27,0.784 sec,4.0,935.949645,464.450818,8.760017e+05,743.041249,385.320500,5.521103e+05
5,,2020-02-29 15:20:28,0.955 sec,5.0,910.686395,452.914250,8.293497e+05,717.709332,372.436091,5.151067e+05
6,,2020-02-29 15:20:28,1.093 sec,6.0,868.738123,435.891538,7.547059e+05,694.828619,361.663909,4.827868e+05
7,,2020-02-29 15:20:28,1.249 sec,7.0,843.042630,423.941471,7.107209e+05,680.899767,354.830631,4.636245e+05
8,,2020-02-29 15:20:28,1.459 sec,8.0,819.467804,414.471815,6.715275e+05,675.444665,351.366078,4.562255e+05
9,,2020-02-29 15:20:28,1.668 sec,9.0,802.676275,407.683137,6.442892e+05,670.355419,348.717463,4.493764e+05
10,,2020-02-29 15:20:29,1.915 sec,10.0,794.301037,402.973652,6.309141e+05,667.154312,346.130216,4.450949e+05
11,,2020-02-29 15:20:29,2.074 sec,11.0,786.132068,399.094846,6.180036e+05,665.920795,345.881215,4.434505e+05
12,,2020-02-29 15:20:29,2.236 sec,12.0,767.898693,391.241244,5.896684e+05,657.835238,340.959573,4.327472e+05
13,,2020-02-29 15:20:29,2.399 sec,13.0,762.525104,387.834472,5.814445e+05,657.721327,340.850547,4.325973e+05
14,,2020-02-29 15:20:29,2.571 sec,14.0,753.631807,384.382721,5.679609e+05,657.934687,340.133810,4.328781e+05
15,,2020-02-29 15:20:29,2.743 sec,15.0,747.342076,381.093700,5.585202e+05,655.320514,338.373554,4.294450e+05
16,,2020-02-29 15:20:30,2.914 sec,16.0,742.258462,378.482952,5.509476e+05,655.744120,338.194302,4.300004e+05
17,,2020-02-29 15:20:30,3.077 sec,17.0,734.950271,375.610590,5.401519e+05,657.948266,338.572289,4.328959e+05
18,,2020-02-29 15:20:30,3.259 sec,18.0,727.909345,372.085506,5.298520e+05,652.440195,336.831356,4.256782e+05
19,,2020-02-29 15:20:30,3.420 sec,19.0,719.908615,368.656718,5.182684e+05,646.699513,334.521741,4.182203e+05

See the whole table with table.as_data_frame()

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0    carat         3.427947e+12           1.000000    0.356506
1        y         2.099399e+12           0.612436    0.218337
2        x         2.027820e+12           0.591555    0.210893
3        z         1.375171e+12           0.401165    0.143017
4  clarity         3.350171e+11           0.097731    0.034842
5    color         2.242404e+11           0.065415    0.023321
6    depth         5.170419e+10           0.015083    0.005377
7    table         3.741624e+10           0.010915    0.003891
8      cut         3.668796e+10           0.010703    0.003816

In [41]:
# We remove the variables that contribute the least to the model

diam_forest_v2 = H2ORandomForestEstimator(
    model_id="rf_covType_v1",
    ntrees=100,
    stopping_rounds=2,
    score_each_iteration=True,
    seed=1000000)
diam_forest_v2.train(['carat', 'y','x','z','clarity','color','depth'], diam_y, training_frame=train, validation_frame=test)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [42]:
diam_forest_v1

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  rf_covType_v1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,22.0,22.0,4096757.0,20.0,20.0,20.0,13874.0,15453.0,14840.954

ModelMetricsRegression: drf
** Reported on train data. **

MSE: 504640.32280053693
RMSE: 710.3804071063172
MAE: 363.9243017902195
RMSLE: 0.12207354888073972
Mean Residual Deviance: 504640.32280053693

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 418885.66127978073
RMSE: 647.2137678385564
MAE: 335.1927374996122
RMSLE: 0.1113102546303575
Mean Residual Deviance: 418885.66127978073

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance,validation_rmse,validation_mae,validation_deviance
0,,2020-02-29 15:20:27,0.001 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-29 15:20:27,0.262 sec,1.0,1076.294994,524.230579,1.158411e+06,1131.391761,551.766427,1.280047e+06
2,,2020-02-29 15:20:27,0.408 sec,2.0,1037.314133,502.309669,1.076021e+06,902.542274,452.480205,8.145826e+05
3,,2020-02-29 15:20:27,0.571 sec,3.0,988.308257,481.866848,9.767532e+05,785.058501,404.036113,6.163168e+05
4,,2020-02-29 15:20:27,0.784 sec,4.0,935.949645,464.450818,8.760017e+05,743.041249,385.320500,5.521103e+05
5,,2020-02-29 15:20:28,0.955 sec,5.0,910.686395,452.914250,8.293497e+05,717.709332,372.436091,5.151067e+05
6,,2020-02-29 15:20:28,1.093 sec,6.0,868.738123,435.891538,7.547059e+05,694.828619,361.663909,4.827868e+05
7,,2020-02-29 15:20:28,1.249 sec,7.0,843.042630,423.941471,7.107209e+05,680.899767,354.830631,4.636245e+05
8,,2020-02-29 15:20:28,1.459 sec,8.0,819.467804,414.471815,6.715275e+05,675.444665,351.366078,4.562255e+05
9,,2020-02-29 15:20:28,1.668 sec,9.0,802.676275,407.683137,6.442892e+05,670.355419,348.717463,4.493764e+05
10,,2020-02-29 15:20:29,1.915 sec,10.0,794.301037,402.973652,6.309141e+05,667.154312,346.130216,4.450949e+05
11,,2020-02-29 15:20:29,2.074 sec,11.0,786.132068,399.094846,6.180036e+05,665.920795,345.881215,4.434505e+05
12,,2020-02-29 15:20:29,2.236 sec,12.0,767.898693,391.241244,5.896684e+05,657.835238,340.959573,4.327472e+05
13,,2020-02-29 15:20:29,2.399 sec,13.0,762.525104,387.834472,5.814445e+05,657.721327,340.850547,4.325973e+05
14,,2020-02-29 15:20:29,2.571 sec,14.0,753.631807,384.382721,5.679609e+05,657.934687,340.133810,4.328781e+05
15,,2020-02-29 15:20:29,2.743 sec,15.0,747.342076,381.093700,5.585202e+05,655.320514,338.373554,4.294450e+05
16,,2020-02-29 15:20:30,2.914 sec,16.0,742.258462,378.482952,5.509476e+05,655.744120,338.194302,4.300004e+05
17,,2020-02-29 15:20:30,3.077 sec,17.0,734.950271,375.610590,5.401519e+05,657.948266,338.572289,4.328959e+05
18,,2020-02-29 15:20:30,3.259 sec,18.0,727.909345,372.085506,5.298520e+05,652.440195,336.831356,4.256782e+05
19,,2020-02-29 15:20:30,3.420 sec,19.0,719.908615,368.656718,5.182684e+05,646.699513,334.521741,4.182203e+05

See the whole table with table.as_data_frame()

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0    carat         3.427947e+12           1.000000    0.356506
1        y         2.099399e+12           0.612436    0.218337
2        x         2.027820e+12           0.591555    0.210893
3        z         1.375171e+12           0.401165    0.143017
4  clarity         3.350171e+11           0.097731    0.034842
5    color         2.242404e+11           0.065415    0.023321
6    depth         5.170419e+10           0.015083    0.005377
7    table         3.741624e+10           0.010915    0.003891
8      cut         3.668796e+10           0.010703    0.003816

In [43]:
diam_forest_v3 = H2ORandomForestEstimator(
    model_id="rf_covType_v1",
    ntrees=10,
    stopping_rounds=2,
    score_each_iteration=True,
    seed=1000000)
diam_forest_v3.train(['carat', 'y','x','z','clarity','color'], diam_y, training_frame=train, validation_frame=test)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [44]:
diam_forest_v3.rmse

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  rf_covType_v1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,10.0,10.0,1815369.0,20.0,20.0,20.0,13923.0,15054.0,14464.4

ModelMetricsRegression: drf
** Reported on train data. **

MSE: 642492.6026672422
RMSE: 801.5563627513926
MAE: 401.05526264259305
RMSLE: 0.13496794953783067
Mean Residual Deviance: 642492.6026672422

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 464271.5714955302
RMSE: 681.3747658194645
MAE: 348.86400933189555
RMSLE: 0.11423548479778194
Mean Residual Deviance: 464271.5714955302

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance,validation_rmse,validation_mae,validation_deviance
0,,2020-02-29 15:20:36,0.001 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-29 15:20:37,0.154 sec,1.0,1095.736382,521.330645,1.200638e+06,1133.441784,538.194123,1.284690e+06
2,,2020-02-29 15:20:37,0.306 sec,2.0,1078.288844,510.329503,1.162707e+06,908.583241,452.445292,8.255235e+05
3,,2020-02-29 15:20:37,0.416 sec,3.0,1028.078732,488.384666,1.056946e+06,823.571143,411.887792,6.782694e+05
4,,2020-02-29 15:20:37,0.533 sec,4.0,962.561492,465.869733,9.265246e+05,769.451679,388.301248,5.920559e+05
5,,2020-02-29 15:20:37,0.650 sec,5.0,916.570226,446.069675,8.401010e+05,740.180945,372.837724,5.478678e+05
6,,2020-02-29 15:20:37,0.764 sec,6.0,882.680033,433.083671,7.791240e+05,720.393774,364.921260,5.189672e+05
7,,2020-02-29 15:20:37,0.884 sec,7.0,848.514632,417.232989,7.199771e+05,700.780178,354.613149,4.910929e+05
8,,2020-02-29 15:20:37,1.002 sec,8.0,838.783876,414.167029,7.035584e+05,697.625139,354.196425,4.866808e+05
9,,2020-02-29 15:20:38,1.134 sec,9.0,819.915100,407.743240,6.722608e+05,692.279588,352.160448,4.792510e+05
10,,2020-02-29 15:20:38,1.278 sec,10.0,801.556363,401.055263,6.424926e+05,681.374766,348.864009,4.642716e+05

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0        y         1.481259e+12           1.000000    0.343809
1    carat         1.077639e+12           0.727516    0.250126
2        x         7.973743e+11           0.538308    0.185075
3        z         6.742045e+11           0.455156    0.156487
4  clarity         1.677452e+11           0.113245    0.038935
5    color         1.101583e+11           0.074368    0.025568

## Initial result

Let us predict the test cases, and get an initial result to submit.

In [45]:

diam_forest_v3

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  rf_covType_v1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,10.0,10.0,1815369.0,20.0,20.0,20.0,13923.0,15054.0,14464.4

ModelMetricsRegression: drf
** Reported on train data. **

MSE: 642492.6026672422
RMSE: 801.5563627513926
MAE: 401.05526264259305
RMSLE: 0.13496794953783067
Mean Residual Deviance: 642492.6026672422

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 464271.5714955302
RMSE: 681.3747658194645
MAE: 348.86400933189555
RMSLE: 0.11423548479778194
Mean Residual Deviance: 464271.5714955302

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance,validation_rmse,validation_mae,validation_deviance
0,,2020-02-29 15:20:36,0.001 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-29 15:20:37,0.154 sec,1.0,1095.736382,521.330645,1.200638e+06,1133.441784,538.194123,1.284690e+06
2,,2020-02-29 15:20:37,0.306 sec,2.0,1078.288844,510.329503,1.162707e+06,908.583241,452.445292,8.255235e+05
3,,2020-02-29 15:20:37,0.416 sec,3.0,1028.078732,488.384666,1.056946e+06,823.571143,411.887792,6.782694e+05
4,,2020-02-29 15:20:37,0.533 sec,4.0,962.561492,465.869733,9.265246e+05,769.451679,388.301248,5.920559e+05
5,,2020-02-29 15:20:37,0.650 sec,5.0,916.570226,446.069675,8.401010e+05,740.180945,372.837724,5.478678e+05
6,,2020-02-29 15:20:37,0.764 sec,6.0,882.680033,433.083671,7.791240e+05,720.393774,364.921260,5.189672e+05
7,,2020-02-29 15:20:37,0.884 sec,7.0,848.514632,417.232989,7.199771e+05,700.780178,354.613149,4.910929e+05
8,,2020-02-29 15:20:37,1.002 sec,8.0,838.783876,414.167029,7.035584e+05,697.625139,354.196425,4.866808e+05
9,,2020-02-29 15:20:38,1.134 sec,9.0,819.915100,407.743240,6.722608e+05,692.279588,352.160448,4.792510e+05
10,,2020-02-29 15:20:38,1.278 sec,10.0,801.556363,401.055263,6.424926e+05,681.374766,348.864009,4.642716e+05

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0        y         1.481259e+12           1.000000    0.343809
1    carat         1.077639e+12           0.727516    0.250126
2        x         7.973743e+11           0.538308    0.185075
3        z         6.742045e+11           0.455156    0.156487
4  clarity         1.677452e+11           0.113245    0.038935
5    color         1.101583e+11           0.074368    0.025568

In [46]:
diam_test = h2o.import_file(path='../cleaned-data/01-diamonds-test-cl.csv')

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [47]:
diam_test

id,carat,cut,color,clarity,depth,table,x,y,z
0,1.1,3,3,3,62.2,58,6.69,6.6,4.13
1,0.51,4,2,1,62.5,57,5.07,5.1,3.18
2,2.03,3,4,1,61.9,59,8.14,8.09,5.02
3,1.21,3,5,1,60,60,6.96,6.91,4.16
4,0.55,4,5,1,61.8,55,5.27,5.22,3.24
5,0.7,3,3,1,61.1,58,5.74,5.79,3.52
6,0.59,4,6,4,60.2,61,5.43,5.47,3.28
7,0.54,4,3,6,61.9,54,5.22,5.25,3.24
8,0.9,3,7,3,58.1,60,6.26,6.24,3.63
9,1.33,4,5,5,60.2,57,7.12,7.17,4.3

In [48]:
diam_test['price'] = diam_forest_v3.predict(diam_test)

drf prediction progress: |████████████████████████████████████████████████| 100%

In [49]:
pred_test = diam_test[['id','price']]

In [50]:
#h2o.export_file(pred_test, '../predictions/01-RDF-H20.csv')

In [51]:
from h2o.estimators import deeplearning

In [52]:
deep_diam_v1 = deeplearning.H2ODeepLearningEstimator()

In [53]:
type(diam_df_train)

h2o.frame.H2OFrame

In [54]:
diam_reduced = diam_df_train.drop([1,5])
dl_train, dl_test = diam_reduced.split_frame([0.8])
dl_train

cut,clarity,depth,table,y,z,price
3,0,61.5,58,5.98,3.66,3446
4,1,60.8,56,4.32,2.64,732
4,1,62.3,54,4.34,2.69,475
4,2,62,58,6.46,4.03,9552
4,1,61.4,55,5.62,3.44,1276
3,3,62.2,60,6.19,3.84,3662
2,1,62.3,55,4.36,2.71,446
0,4,64.6,59,5.59,3.62,2902
4,1,62.4,57,8.09,5.08,18193
2,0,59.9,61,6.91,4.12,5644

In [55]:
deep_diam_v1.train(x=diam_reduced[:-1].columns, y=diam_reduced[-1].columns[0], training_frame=dl_train,  validation_frame=dl_test)

deeplearning Model Build progress: |██████████████████████████████████████| 100%

In [56]:
deep_diam_v1

Model Details
=============
H2ODeepLearningEstimator :  Deep Learning
Model Key:  DeepLearning_model_python_1582981961797_5


Status of Neuron Layers: predicting price, regression, gaussian distribution, Quadratic loss, 41,801 weights/biases, 500.5 KB, 322,640 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,6,Input,0,,,,,,,,,
1,,2,200,Rectifier,0,0,0,0.0118183,0.0142538,0,-0.027585,0.11483,0.410967,0.119434
2,,3,200,Rectifier,0,0,0,0.307227,0.267774,0,-0.0344028,0.0993225,0.921924,0.145116
3,,4,1,Linear,,0,0,0.00238632,0.00174419,0,-0.00970953,0.0586164,0.219476,1.09713e-154

ModelMetricsRegression: deeplearning
** Reported on train data. **

MSE: 1354323.9733799733
RMSE: 1163.7542581576117
MAE: 652.5910449687279
RMSLE: NaN
Mean Residual Deviance: 1354323.9733799733

ModelMetricsRegression: deeplearning
** Reported on validation data. **

MSE: 1364837.7605339242
RMSE: 1168.2627104097453
MAE: 665.8745618870254
RMSLE: 0.24685243948102864
Mean Residual Deviance: 1364837.7605339242

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2,validation_rmse,validation_deviance,validation_mae,validation_r2
0,,2020-02-29 15:20:39,0.000 sec,None,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-29 15:20:42,2.574 sec,14579 obs/sec,1.0,1,32264.0,1434.784885,2.058608e+06,754.751790,0.871695,1387.495173,1.925143e+06,766.112769,0.884580
2,,2020-02-29 15:20:47,8.108 sec,34078 obs/sec,8.0,8,258112.0,1180.295063,1.393096e+06,657.144195,0.913174,1179.884244,1.392127e+06,666.563426,0.916537
3,,2020-02-29 15:20:49,9.601 sec,36198 obs/sec,10.0,10,322640.0,1163.754258,1.354324e+06,652.591045,0.915590,1168.262710,1.364838e+06,665.874562,0.918173

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0  clarity             1.000000           1.000000    0.284384
1        y             0.995368           0.995368    0.283066
2        z             0.832916           0.832916    0.236868
3    table             0.240969           0.240969    0.068528
4      cut             0.229845           0.229845    0.065364
5    depth             0.217278           0.217278    0.061790

In [66]:
pred_test2 = deep_diam_v1.predict(diam_test)
pred_test = df[pred_test2]

deeplearning prediction progress: |███████████████████████████████████████| 100%

NameError: name 'df' is not defined

In [ ]:
pred_test2

In [ ]:
diam_test['price'] = deep_diam_v1.predict(diam_test)

In [ ]:
diam_testv2 = diam_test[['id','price']]

In [ ]:
h2o.export_file(diam_testv2, '../predictions/02-Deep-Learning-H20.csv')

In [ ]:
diam_reduced = diam_df_train.drop

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%

In [65]:
display(dum_train)
display(dum_test)

carat,depth,table,x,y,z,cut_0,cut_1,cut_2,cut_3,cut_4,color_1,color_2,color_3,color_4,color_5,color_6,color_7,clarity_0,clarity_1,clarity_2,clarity_3,clarity_4,clarity_5,clarity_6,clarity_7,price
0.78,61.5,58,5.93,5.98,3.66,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,3446
0.31,60.8,56,4.37,4.32,2.64,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,732
0.3,62.3,54,4.3,4.34,2.69,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,475
1.04,62,58,6.54,6.46,4.03,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,9552
0.65,61.4,55,5.58,5.62,3.44,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1276
0.9,62.2,60,6.15,6.19,3.84,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,3662
0.31,62.3,55,4.34,4.36,2.71,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,446
0.71,64.6,59,5.62,5.59,3.62,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,2902
2.05,62.4,57,8.17,8.09,5.08,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,18193
1.1,61.3,58,6.64,6.71,4.09,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,4791

carat,depth,table,x,y,z,cut_0,cut_1,cut_2,cut_3,cut_4,color_1,color_2,color_3,color_4,color_5,color_6,color_7,clarity_0,clarity_1,clarity_2,clarity_3,clarity_4,clarity_5,clarity_6,clarity_7
1.1,62.2,58,6.69,6.6,4.13,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
0.51,62.5,57,5.07,5.1,3.18,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
2.03,61.9,59,8.14,8.09,5.02,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
1.21,60,60,6.96,6.91,4.16,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0
0.55,61.8,55,5.27,5.22,3.24,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0
0.7,61.1,58,5.74,5.79,3.52,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
0.59,60.2,61,5.43,5.47,3.28,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0
0.54,61.9,54,5.22,5.25,3.24,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
0.9,58.1,60,6.26,6.24,3.63,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1.33,60.2,57,7.12,7.17,4.3,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0