In [2]:
import h2o
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.6" 2020-01-14; OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1); OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
  Starting server from /home/edu/.local/lib/python3.7/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpl5gc080i
  JVM stdout: /tmp/tmpl5gc080i/h2o_edu_started_from_python.out
  JVM stderr: /tmp/tmpl5gc080i/h2o_edu_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ------------------------------------------------------------------
H2O cluster uptime:         01 secs
H2O cluster timezone:       Europe/Paris
H2O data parsing timezone:  UTC
H2O cluster version:        3.28.0.3
H2O cluster version age:    23 days
H2O cluster name:           H2O_from_python_edu_1ahlr2
H2O cluster total nodes:    1
H2O cluster free memory:    1.887 Gb
H2O cluster total cores:    8
H2O cluster allowed cores:  8
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:       {'http': None, 'https': None}
H2O internal security:      False
H2O API Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python version:             3.7.6 final
--------------------------  ------------------------------------------------------------------

In [34]:
from h2o.estimators.gbm import H2OGradientBoostingEstimator
diamond_path = '../cleaned-data/01-diamonds-train-cl.csv'
diam_df = h2o.import_file(path=diamond_path).drop(0, axis=1)
diam_df.describe()

Parse progress: |█████████████████████████████████████████████████████████| 100%
Rows:40345
Cols:10

,carat,cut,color,clarity,depth,table,x,y,z,price
type,real,int,int,int,real,real,real,real,real,int
mins,0.2,0.0,1.0,0.0,43.0,43.0,0.0,0.0,0.0,326.0
mean,0.7976990953030115,2.905936299417525,4.40651877556079,2.5241293840624612,61.7497211550378,57.449421241789565,5.7308236460527935,5.734807782872725,3.537958111290122,3931.902243152807
maxs,5.01,4.0,7.0,7.0,79.0,95.0,10.74,58.9,8.06,18823.0
sigma,0.47430905911318594,1.1154151728126476,1.7006671128832476,1.839946880272431,1.4277278054903706,2.234087256614312,1.1217667368900286,1.1515362870115242,0.695039090575716,3994.318831718142
zeros,0,1202,0,6092,0,0,4,3,14,0
missing,0,0,0,0,0,0,0,0,0,0
0,0.78,3.0,5.0,0.0,61.5,58.0,5.93,5.98,3.66,3446.0
1,0.31,4.0,7.0,1.0,60.8,56.0,4.37,4.32,2.64,732.0
2,0.3,4.0,5.0,1.0,62.3,54.0,4.3,4.34,2.69,475.0
3,1.04,4.0,6.0,2.0,62.0,58.0,6.54,6.46,4.03,9552.0
4,0.65,4.0,1.0,1.0,61.4,55.0,5.58,5.62,3.44,1276.0
5,0.9,3.0,6.0,3.0,62.2,60.0,6.15,6.19,3.84,3662.0
6,0.31,2.0,3.0,1.0,62.3,55.0,4.34,4.36,2.71,446.0
7,0.71,0.0,6.0,4.0,64.6,59.0,5.62,5.59,3.62,2902.0
8,2.05,4.0,6.0,1.0,62.4,57.0,8.17,8.09,5.08,18193.0
9,1.1,2.0,6.0,1.0,61.3,58.0,6.64,6.71,4.09,4791.0

In [9]:
diam_df_train = diam_df.drop(0, axis=1)
print(list(enumerate(diam_df_train.columns)))
diam_df_train

[(0, 'carat'),
 (1, 'cut'),
 (2, 'color'),
 (3, 'clarity'),
 (4, 'depth'),
 (5, 'table'),
 (6, 'x'),
 (7, 'y'),
 (8, 'z'),
 (9, 'price')]

In [24]:
gbm_regressor = H2OGradientBoostingEstimator(distribution="gaussian",
ntrees=10, max_depth=4, min_rows=2, learn_rate=0.2)

In [25]:
gbm_regressor.train(x=diam_df_train.columns[:-1], y='price', training_frame=diam_df_train)

gbm Model Build progress: |███████████████████████████████████████████████| 100%

In [27]:
gbm_regressor

Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_model_python_1582914750378_4


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,10.0,10.0,2580.0,4.0,4.0,4.0,16.0,16.0,16.0

ModelMetricsRegression: gbm
** Reported on train data. **

MSE: 1291590.2222788846
RMSE: 1136.4815098710953
MAE: 699.2130565870708
RMSLE: 0.32098582074044096
Mean Residual Deviance: 1291590.2222788846

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance
0,,2020-02-28 19:51:10,0.001 sec,0.0,3994.269329,3033.569481,1.595419e+07
1,,2020-02-28 19:51:10,0.063 sec,1.0,3286.728348,2460.049901,1.080258e+07
2,,2020-02-28 19:51:10,0.100 sec,2.0,2736.975975,2017.615556,7.491037e+06
3,,2020-02-28 19:51:10,0.126 sec,3.0,2313.801537,1677.011629,5.353678e+06
4,,2020-02-28 19:51:10,0.150 sec,4.0,1977.982425,1391.155978,3.912414e+06
5,,2020-02-28 19:51:10,0.168 sec,5.0,1727.970425,1187.853736,2.985882e+06
6,,2020-02-28 19:51:10,0.190 sec,6.0,1543.944534,1038.068731,2.383765e+06
7,,2020-02-28 19:51:10,0.212 sec,7.0,1400.588823,920.884497,1.961649e+06
8,,2020-02-28 19:51:10,0.227 sec,8.0,1289.692940,829.773802,1.663308e+06
9,,2020-02-28 19:51:10,0.245 sec,9.0,1198.983994,754.494386,1.437563e+06
10,,2020-02-28 19:51:10,0.259 sec,10.0,1136.481510,699.213057,1.291590e+06

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0        y         8.695758e+11           1.000000    0.529170
1    carat         6.226457e+11           0.716034    0.378903
2        z         6.241700e+10           0.071779    0.037983
3  clarity         4.396779e+10           0.050562    0.026756
4    color         4.149371e+10           0.047717    0.025250
5        x         2.360024e+09           0.002714    0.001436
6      cut         8.231659e+08           0.000947    0.000501
7    depth         0.000000e+00           0.000000    0.000000
8    table         0.000000e+00           0.000000    0.000000

In [42]:
train, test = diam_df.split_frame([0.8], seed=1234)
gbm_regressor.train(x=train.columns[:-1], y='price', training_frame=train)

gbm Model Build progress: |███████████████████████████████████████████████| 100%

In [31]:
gbm_regressor.predict(test).shape

gbm prediction progress: |████████████████████████████████████████████████| 100%

(7955, 1)

In [32]:
from h2o.estimators.random_forest import H2ORandomForestEstimator

In [35]:
diam_X = diam_df.col_names[:-1]     #last column is price, our desired response variable 
diam_y = diam_df.col_names[-1]

In [33]:
diam_df

id,carat,cut,color,clarity,depth,table,x,y,z,price
0,0.78,3,5,0,61.5,58,5.93,5.98,3.66,3446
1,0.31,4,7,1,60.8,56,4.37,4.32,2.64,732
2,0.3,4,5,1,62.3,54,4.3,4.34,2.69,475
3,1.04,4,6,2,62,58,6.54,6.46,4.03,9552
4,0.65,4,1,1,61.4,55,5.58,5.62,3.44,1276
5,0.9,3,6,3,62.2,60,6.15,6.19,3.84,3662
6,0.31,2,3,1,62.3,55,4.34,4.36,2.71,446
7,0.71,0,6,4,64.6,59,5.62,5.59,3.62,2902
8,2.05,4,6,1,62.4,57,8.17,8.09,5.08,18193
9,1.1,2,6,1,61.3,58,6.64,6.71,4.09,4791

In [43]:
diam_forest_v1 = H2ORandomForestEstimator(
    model_id="rf_covType_v1",
    ntrees=100,
    stopping_rounds=2,
    score_each_iteration=True,
    seed=1000000)
diam_forest_v1.train(diam_X, diam_y, training_frame=train, validation_frame=test)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [45]:
diam_forest_v1

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  rf_covType_v1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,22.0,22.0,4096756.0,20.0,20.0,20.0,13874.0,15453.0,14840.954

ModelMetricsRegression: drf
** Reported on train data. **

MSE: 504640.32280053693
RMSE: 710.3804071063172
MAE: 363.9243017902195
RMSLE: 0.12207354888073972
Mean Residual Deviance: 504640.32280053693

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 418885.66127978073
RMSE: 647.2137678385564
MAE: 335.1927374996122
RMSLE: 0.1113102546303575
Mean Residual Deviance: 418885.66127978073

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance,validation_rmse,validation_mae,validation_deviance
0,,2020-02-28 20:06:56,0.001 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-28 20:06:57,0.197 sec,1.0,1076.294994,524.230579,1.158411e+06,1131.391761,551.766427,1.280047e+06
2,,2020-02-28 20:06:57,0.372 sec,2.0,1037.314133,502.309669,1.076021e+06,902.542274,452.480205,8.145826e+05
3,,2020-02-28 20:06:57,0.514 sec,3.0,988.308257,481.866848,9.767532e+05,785.058501,404.036113,6.163168e+05
4,,2020-02-28 20:06:57,0.661 sec,4.0,935.949645,464.450818,8.760017e+05,743.041249,385.320500,5.521103e+05
5,,2020-02-28 20:06:57,0.855 sec,5.0,910.686395,452.914250,8.293497e+05,717.709332,372.436091,5.151067e+05
6,,2020-02-28 20:06:58,1.061 sec,6.0,868.738123,435.891538,7.547059e+05,694.828619,361.663909,4.827868e+05
7,,2020-02-28 20:06:58,1.262 sec,7.0,843.042630,423.941471,7.107209e+05,680.899767,354.830631,4.636245e+05
8,,2020-02-28 20:06:58,1.433 sec,8.0,819.467804,414.471815,6.715275e+05,675.444665,351.366078,4.562255e+05
9,,2020-02-28 20:06:58,1.585 sec,9.0,802.676275,407.683137,6.442892e+05,670.355419,348.717463,4.493764e+05
10,,2020-02-28 20:06:58,1.729 sec,10.0,794.301037,402.973652,6.309141e+05,667.154312,346.130216,4.450949e+05
11,,2020-02-28 20:06:58,1.881 sec,11.0,786.132068,399.094846,6.180036e+05,665.920795,345.881215,4.434505e+05
12,,2020-02-28 20:06:58,2.034 sec,12.0,767.898693,391.241244,5.896684e+05,657.835238,340.959573,4.327472e+05
13,,2020-02-28 20:06:59,2.207 sec,13.0,762.525104,387.834472,5.814445e+05,657.721327,340.850547,4.325973e+05
14,,2020-02-28 20:06:59,2.396 sec,14.0,753.631807,384.382721,5.679609e+05,657.934687,340.133810,4.328781e+05
15,,2020-02-28 20:06:59,2.555 sec,15.0,747.342076,381.093700,5.585202e+05,655.320514,338.373554,4.294450e+05
16,,2020-02-28 20:06:59,2.741 sec,16.0,742.258462,378.482952,5.509476e+05,655.744120,338.194302,4.300004e+05
17,,2020-02-28 20:06:59,2.909 sec,17.0,734.950271,375.610590,5.401519e+05,657.948266,338.572289,4.328959e+05
18,,2020-02-28 20:07:00,3.096 sec,18.0,727.909345,372.085506,5.298520e+05,652.440195,336.831356,4.256782e+05
19,,2020-02-28 20:07:00,3.271 sec,19.0,719.908615,368.656718,5.182684e+05,646.699513,334.521741,4.182203e+05

See the whole table with table.as_data_frame()

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0    carat         3.427947e+12           1.000000    0.356506
1        y         2.099399e+12           0.612436    0.218337
2        x         2.027820e+12           0.591555    0.210893
3        z         1.375171e+12           0.401165    0.143017
4  clarity         3.350171e+11           0.097731    0.034842
5    color         2.242404e+11           0.065415    0.023321
6    depth         5.170419e+10           0.015083    0.005377
7    table         3.741624e+10           0.010915    0.003891
8      cut         3.668796e+10           0.010703    0.003816

In [46]:
# We remove the variables that contribute the least to the model

diam_forest_v2 = H2ORandomForestEstimator(
    model_id="rf_covType_v1",
    ntrees=100,
    stopping_rounds=2,
    score_each_iteration=True,
    seed=1000000)
diam_forest_v2.train(['carat', 'y','x','z','clarity','color','depth'], diam_y, training_frame=train, validation_frame=test)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [47]:
diam_forest_v1

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  rf_covType_v1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,28.0,28.0,4961311.0,20.0,20.0,20.0,12999.0,14982.0,14119.179

ModelMetricsRegression: drf
** Reported on train data. **

MSE: 519798.27322399884
RMSE: 720.9703691719923
MAE: 371.41633000222095
RMSLE: 0.12471626699150332
Mean Residual Deviance: 519798.27322399884

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 461402.0511940528
RMSE: 679.2658177724335
MAE: 353.0351419050668
RMSLE: 0.1164591059975335
Mean Residual Deviance: 461402.0511940528

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance,validation_rmse,validation_mae,validation_deviance
0,,2020-02-28 20:10:22,0.001 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-28 20:10:22,0.168 sec,1.0,1267.637656,593.288230,1.606905e+06,1271.816398,597.959452,1.617517e+06
2,,2020-02-28 20:10:22,0.293 sec,2.0,1180.697924,559.419083,1.394048e+06,994.405869,494.692556,9.888430e+05
3,,2020-02-28 20:10:22,0.408 sec,3.0,1110.946378,537.547652,1.234202e+06,910.690279,459.753313,8.293568e+05
4,,2020-02-28 20:10:22,0.507 sec,4.0,1054.647772,514.801156,1.112282e+06,841.514777,431.145452,7.081471e+05
5,,2020-02-28 20:10:22,0.620 sec,5.0,1001.527443,494.799281,1.003057e+06,792.275053,409.088175,6.276998e+05
6,,2020-02-28 20:10:23,0.735 sec,6.0,947.161604,472.015964,8.971151e+05,759.635646,393.836283,5.770463e+05
7,,2020-02-28 20:10:23,0.855 sec,7.0,918.375509,459.427185,8.434136e+05,749.136422,389.331984,5.612054e+05
8,,2020-02-28 20:10:23,0.956 sec,8.0,889.317032,449.532066,7.908848e+05,740.657798,383.698048,5.485740e+05
9,,2020-02-28 20:10:23,1.109 sec,9.0,872.044650,442.822929,7.604619e+05,739.729048,383.483463,5.471991e+05
10,,2020-02-28 20:10:23,1.254 sec,10.0,846.505576,431.777361,7.165717e+05,731.069389,377.657207,5.344625e+05
11,,2020-02-28 20:10:23,1.374 sec,11.0,824.669411,422.095963,6.800796e+05,720.716716,372.347925,5.194326e+05
12,,2020-02-28 20:10:23,1.486 sec,12.0,802.990483,413.096654,6.447937e+05,710.327288,367.356039,5.045649e+05
13,,2020-02-28 20:10:23,1.608 sec,13.0,798.500448,411.184929,6.376030e+05,714.343393,368.270035,5.102865e+05
14,,2020-02-28 20:10:24,1.723 sec,14.0,789.158136,406.764556,6.227706e+05,713.199678,367.912619,5.086538e+05
15,,2020-02-28 20:10:24,1.843 sec,15.0,781.694175,402.322442,6.110458e+05,707.706408,366.143404,5.008484e+05
16,,2020-02-28 20:10:24,1.965 sec,16.0,773.798590,399.376703,5.987643e+05,707.740787,366.342907,5.008970e+05
17,,2020-02-28 20:10:24,2.079 sec,17.0,768.127536,396.874019,5.900199e+05,705.843932,365.824424,4.982157e+05
18,,2020-02-28 20:10:24,2.209 sec,18.0,762.009421,394.576630,5.806584e+05,700.923268,364.552790,4.912934e+05
19,,2020-02-28 20:10:24,2.355 sec,19.0,753.714173,390.270217,5.680851e+05,696.769852,362.421958,4.854882e+05

See the whole table with table.as_data_frame()

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0    carat         3.563024e+12           1.000000    0.290713
1        y         3.178392e+12           0.892049    0.259330
2        z         2.469356e+12           0.693051    0.201479
3        x         2.241941e+12           0.629224    0.182924
4  clarity         4.265404e+11           0.119713    0.034802
5    color         2.855764e+11           0.080150    0.023301
6    depth         9.133841e+10           0.025635    0.007452

In [62]:
diam_forest_v3 = H2ORandomForestEstimator(
    model_id="rf_covType_v1",
    ntrees=10,
    stopping_rounds=2,
    score_each_iteration=True,
    seed=1000000)
diam_forest_v3.train(['carat', 'y','x','z','clarity','color'], diam_y, training_frame=train, validation_frame=test)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [64]:
diam_forest_v3.rmse

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  rf_covType_v1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,10.0,10.0,1815368.0,20.0,20.0,20.0,13923.0,15054.0,14464.4

ModelMetricsRegression: drf
** Reported on train data. **

MSE: 642492.6026672422
RMSE: 801.5563627513926
MAE: 401.05526264259305
RMSLE: 0.13496794953783067
Mean Residual Deviance: 642492.6026672422

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 464271.5714955302
RMSE: 681.3747658194645
MAE: 348.86400933189555
RMSLE: 0.11423548479778194
Mean Residual Deviance: 464271.5714955302

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance,validation_rmse,validation_mae,validation_deviance
0,,2020-02-28 20:18:23,0.001 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-28 20:18:23,0.132 sec,1.0,1095.736382,521.330645,1.200638e+06,1133.441784,538.194123,1.284690e+06
2,,2020-02-28 20:18:23,0.218 sec,2.0,1078.288844,510.329503,1.162707e+06,908.583241,452.445292,8.255235e+05
3,,2020-02-28 20:18:23,0.320 sec,3.0,1028.078732,488.384666,1.056946e+06,823.571143,411.887792,6.782694e+05
4,,2020-02-28 20:18:24,0.422 sec,4.0,962.561492,465.869733,9.265246e+05,769.451679,388.301248,5.920559e+05
5,,2020-02-28 20:18:24,0.537 sec,5.0,916.570226,446.069675,8.401010e+05,740.180945,372.837724,5.478678e+05
6,,2020-02-28 20:18:24,0.665 sec,6.0,882.680033,433.083671,7.791240e+05,720.393774,364.921260,5.189672e+05
7,,2020-02-28 20:18:24,0.796 sec,7.0,848.514632,417.232989,7.199771e+05,700.780178,354.613149,4.910929e+05
8,,2020-02-28 20:18:24,0.928 sec,8.0,838.783876,414.167029,7.035584e+05,697.625139,354.196425,4.866808e+05
9,,2020-02-28 20:18:24,1.067 sec,9.0,819.915100,407.743240,6.722608e+05,692.279588,352.160448,4.792510e+05
10,,2020-02-28 20:18:24,1.196 sec,10.0,801.556363,401.055263,6.424926e+05,681.374766,348.864009,4.642716e+05

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0        y         1.481259e+12           1.000000    0.343809
1    carat         1.077639e+12           0.727516    0.250126
2        x         7.973743e+11           0.538308    0.185075
3        z         6.742045e+11           0.455156    0.156487
4  clarity         1.677452e+11           0.113245    0.038935
5    color         1.101583e+11           0.074368    0.025568

## Initial result

Let us predict the test cases, and get an initial result to submit.

In [65]:

diam_forest_v3

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  rf_covType_v1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,10.0,10.0,1815368.0,20.0,20.0,20.0,13923.0,15054.0,14464.4

ModelMetricsRegression: drf
** Reported on train data. **

MSE: 642492.6026672422
RMSE: 801.5563627513926
MAE: 401.05526264259305
RMSLE: 0.13496794953783067
Mean Residual Deviance: 642492.6026672422

ModelMetricsRegression: drf
** Reported on validation data. **

MSE: 464271.5714955302
RMSE: 681.3747658194645
MAE: 348.86400933189555
RMSLE: 0.11423548479778194
Mean Residual Deviance: 464271.5714955302

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_mae,training_deviance,validation_rmse,validation_mae,validation_deviance
0,,2020-02-28 20:18:23,0.001 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-28 20:18:23,0.132 sec,1.0,1095.736382,521.330645,1.200638e+06,1133.441784,538.194123,1.284690e+06
2,,2020-02-28 20:18:23,0.218 sec,2.0,1078.288844,510.329503,1.162707e+06,908.583241,452.445292,8.255235e+05
3,,2020-02-28 20:18:23,0.320 sec,3.0,1028.078732,488.384666,1.056946e+06,823.571143,411.887792,6.782694e+05
4,,2020-02-28 20:18:24,0.422 sec,4.0,962.561492,465.869733,9.265246e+05,769.451679,388.301248,5.920559e+05
5,,2020-02-28 20:18:24,0.537 sec,5.0,916.570226,446.069675,8.401010e+05,740.180945,372.837724,5.478678e+05
6,,2020-02-28 20:18:24,0.665 sec,6.0,882.680033,433.083671,7.791240e+05,720.393774,364.921260,5.189672e+05
7,,2020-02-28 20:18:24,0.796 sec,7.0,848.514632,417.232989,7.199771e+05,700.780178,354.613149,4.910929e+05
8,,2020-02-28 20:18:24,0.928 sec,8.0,838.783876,414.167029,7.035584e+05,697.625139,354.196425,4.866808e+05
9,,2020-02-28 20:18:24,1.067 sec,9.0,819.915100,407.743240,6.722608e+05,692.279588,352.160448,4.792510e+05
10,,2020-02-28 20:18:24,1.196 sec,10.0,801.556363,401.055263,6.424926e+05,681.374766,348.864009,4.642716e+05

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0        y         1.481259e+12           1.000000    0.343809
1    carat         1.077639e+12           0.727516    0.250126
2        x         7.973743e+11           0.538308    0.185075
3        z         6.742045e+11           0.455156    0.156487
4  clarity         1.677452e+11           0.113245    0.038935
5    color         1.101583e+11           0.074368    0.025568

In [68]:
diam_test = h2o.import_file(path='../cleaned-data/01-diamonds-test-cl.csv')

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [69]:
diam_test

id,carat,cut,color,clarity,depth,table,x,y,z
0,1.1,3,3,3,62.2,58,6.69,6.6,4.13
1,0.51,4,2,1,62.5,57,5.07,5.1,3.18
2,2.03,3,4,1,61.9,59,8.14,8.09,5.02
3,1.21,3,5,1,60,60,6.96,6.91,4.16
4,0.55,4,5,1,61.8,55,5.27,5.22,3.24
5,0.7,3,3,1,61.1,58,5.74,5.79,3.52
6,0.59,4,6,4,60.2,61,5.43,5.47,3.28
7,0.54,4,3,6,61.9,54,5.22,5.25,3.24
8,0.9,3,7,3,58.1,60,6.26,6.24,3.63
9,1.33,4,5,5,60.2,57,7.12,7.17,4.3

In [71]:
diam_test['price'] = diam_forest_v3.predict(diam_test)

drf prediction progress: |████████████████████████████████████████████████| 100%

In [73]:
pred_test = diam_test[['id','price']]

In [75]:
h2o.export_file(pred_test, '../predictions/01-RDF-H20.csv')

Export File progress: |███████████████████████████████████████████████████| 100%

In [76]:
from h2o.estimators import deeplearning

In [77]:
deep_diam_v1 = deeplearning.H2ODeepLearningEstimator()

In [81]:
type(diam_df_train)

h2o.frame.H2OFrame

In [98]:
diam_reduced = diam_df_train.drop([1,5])
dl_train, dl_test = diam_reduced.split_frame([0.8])
dl_train

carat,color,clarity,depth,x,y,z,price
0.31,7,1,60.8,4.37,4.32,2.64,732
0.65,1,1,61.4,5.58,5.62,3.44,1276
0.9,6,3,62.2,6.15,6.19,3.84,3662
2.05,6,1,62.4,8.17,8.09,5.08,18193
1.19,2,0,59.9,6.85,6.91,4.12,5644
0.65,5,0,62.2,5.6,5.53,3.46,2340
0.3,7,1,61.4,4.35,4.32,2.66,709
0.71,4,1,61.2,5.77,5.79,3.54,2400
0.33,5,5,61.3,4.47,4.5,2.75,1240
1.3,4,2,60.9,7.04,7.11,4.31,11853

In [102]:
deep_diam_v1.train(x=diam_reduced[:-1].columns, y=diam_reduced[-1].columns[0], training_frame=dl_train,  validation_frame=dl_test)

deeplearning Model Build progress: |██████████████████████████████████████| 100%

In [103]:
deep_diam_v1

Model Details
=============
H2ODeepLearningEstimator :  Deep Learning
Model Key:  DeepLearning_model_python_1582914750378_11


Status of Neuron Layers: predicting price, regression, gaussian distribution, Quadratic loss, 42,001 weights/biases, 503.4 KB, 322,700 training samples, mini-batch size 1

,,layer,units,type,dropout,l1,l2,mean_rate,rate_rms,momentum,mean_weight,weight_rms,mean_bias,bias_rms
0,,1,7,Input,0,,,,,,,,,
1,,2,200,Rectifier,0,0,0,0.00962848,0.0126526,0,-0.0145279,0.151192,0.423418,0.0954309
2,,3,200,Rectifier,0,0,0,0.266553,0.285745,0,-0.0352053,0.111647,0.919743,0.155071
3,,4,1,Linear,,0,0,0.00284142,0.00297263,0,0.00436722,0.0847411,0.273729,1.09713e-154

ModelMetricsRegression: deeplearning
** Reported on train data. **

MSE: 470745.2001919835
RMSE: 686.108737877593
MAE: 381.76585559305624
RMSLE: NaN
Mean Residual Deviance: 470745.2001919835

ModelMetricsRegression: deeplearning
** Reported on validation data. **

MSE: 449170.1716736905
RMSE: 670.2015903246504
MAE: 379.17306338917365
RMSLE: NaN
Mean Residual Deviance: 449170.1716736905

Scoring History:

,,timestamp,duration,training_speed,epochs,iterations,samples,training_rmse,training_deviance,training_mae,training_r2,validation_rmse,validation_deviance,validation_mae,validation_r2
0,,2020-02-28 20:58:42,0.000 sec,None,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,2020-02-28 20:58:43,1.584 sec,22472 obs/sec,1.0,1,32270.0,1176.303872,1.383691e+06,680.844128,0.915319,1131.641504,1.280612e+06,665.185721,0.916266
2,,2020-02-28 20:58:49,7.128 sec,42435 obs/sec,9.0,9,290430.0,656.546152,4.310529e+05,380.379068,0.973620,681.071619,4.638586e+05,389.003440,0.969670
3,,2020-02-28 20:58:50,8.056 sec,42460 obs/sec,10.0,10,322700.0,686.108738,4.707452e+05,381.765856,0.971191,670.201590,4.491702e+05,379.173063,0.970631

Variable Importances:

  variable  relative_importance  scaled_importance  percentage
0  clarity             1.000000           1.000000    0.275220
1    carat             0.590460           0.590460    0.162507
2        y             0.509396           0.509396    0.140196
3    color             0.448590           0.448590    0.123461
4        x             0.438623           0.438623    0.120718
5        z             0.430764           0.430764    0.118555
6    depth             0.215618           0.215618    0.059342

In [86]:
pred_test2 = deep_diam_v1.predict(diam_test)
pred_test = df[pred_test2]

deeplearning prediction progress: |███████████████████████████████████████| 100%

In [87]:
pred_test2

predict
4391.55
1150.58
17000.5
6774.85
1336.61
2054.35
2073.18
1973.89
3419.65
15530.8

In [88]:
diam_test['price'] = deep_diam_v1.predict(diam_test)

deeplearning prediction progress: |███████████████████████████████████████| 100%

In [91]:
diam_testv2 = diam_test[['id','price']]

In [92]:
h2o.export_file(diam_testv2, '../predictions/02-Deep-Learning-H20.csv')

Export File progress: |███████████████████████████████████████████████████| 100%

In [93]:
diam_reduced = diam_df_train.drop

carat,cut,color,clarity,depth,table,x,y,z,price
0.78,3,5,0,61.5,58,5.93,5.98,3.66,3446
0.31,4,7,1,60.8,56,4.37,4.32,2.64,732
0.3,4,5,1,62.3,54,4.3,4.34,2.69,475
1.04,4,6,2,62,58,6.54,6.46,4.03,9552
0.65,4,1,1,61.4,55,5.58,5.62,3.44,1276
0.9,3,6,3,62.2,60,6.15,6.19,3.84,3662
0.31,2,3,1,62.3,55,4.34,4.36,2.71,446
0.71,0,6,4,64.6,59,5.62,5.59,3.62,2902
2.05,4,6,1,62.4,57,8.17,8.09,5.08,18193
1.1,2,6,1,61.3,58,6.64,6.71,4.09,4791